spring:
  application:
    name: common-content
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bz_shop?characterEncoding=UTF-8
    username: root
    password: 1231
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    addresses: 192.168.6.122
    username: blur
    password: 123456
    port: 5672
    virtual-host: /
server:
  port: 9020

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/


tx-lcn:
  client:
    manager-address: 192.168.6.121:8070

frontend:
  AD: 89